### ISSUE TITLE
Inconsistencies when turning on/off light in an area

### ISSUE THREAD

**Issue by denniswham** [home-assistant/intents#1440] opened 2023-07-06 11:18 UTC
Turning on light in an area works, but turning it off doesn't

<img width="299" alt="image" src="https://github.com/home-assistant/intents/assets/43110823/bc34fb71-0d59-4739-b692-5c4ca4e58585">

**Comment by TheFes** [comment] 2023-07-17 07:02
Sorry, missed this one, thanks for assigning it @tetele

**Comment by TheFes** [comment] 2023-07-17 11:33
Hmm, strange, I can't reproduce this:
![image](https://github.com/home-assistant/intents/assets/28803438/2c0b1346-7204-4179-bf83-131ed6100c99)

This is in my own productions system running HA 2023.7.2

I also tested in the intents repo using the test scripts there, and also there it works without issues.

**Comment by TheFes** [comment] 2023-07-17 11:34
Could you test in developer tools > Assist what happens when you use both sentences?

**Comment by TheFes** [comment] 2023-07-17 12:42
Okay, this helps to reproduce it.
You have a light entity with either the name or alias `licht`

So for the turn on intent it matches `licht` with the expansion rule, and then uses the area `zolder`
However, for the turn off command, it first matches `licht` with the entity with name or alias `licht` and then fails because that light is in another area.

Not sure why it does a different matching on these turn on and off actions @synesthesiam can you maybe enlighten us on that?

However, If you can find the light entity with the name or alias `licht` and rename that, it should work.

**Comment by denniswham** [comment] 2023-07-17 12:48
It starts to make things clear... but not completely yet ;-)

The entity is called Attic Light, and I haven't renamed it. Though I have provided a alias "zolder licht".

<img width="442" alt="image" src="https://github.com/home-assistant/intents/assets/43110823/790e5929-e8d0-4841-b32e-a00cf6fb83d2">

Does that make sense to you?

**Comment by TheFes** [comment] 2023-07-17 12:56
No, I think it's another entity, which is not in the area `zolder`

Could you try this in developer tools > template
[![Open your Home Assistant instance and show your template developer tools.](https://my.home-assistant.io/badges/developer_template.svg)](https://my.home-assistant.io/redirect/developer_template/)

```jinja
{% for l in states.light if l.name | lower == 'licht' %}
  entity_id: {{ l.entity_id }} | name:{{ l.name }}{{ '\n' }}
{% endfor %}
```
Does that return anything?

**Comment by TheFes** [comment] 2023-07-17 13:03
> Keep in mind that it might be an alias, not necessarily a name. And several entities could potentially have the same alias.

Yeah I know, but if it's the name we know the culprit. If it's an alias it could be like finding a needle in a haystack

**Comment by TheFes** [comment] 2023-07-17 13:04
oh wait, you could also go to devtools > assist and try:
`zet licht aan` and `zet licht uit`
does one of those give a reference to a specific entity?

**Comment by denniswham** [comment] 2023-07-17 13:05
> No, I think it's another entity, which is not in the area `zolder`
> 
> Could you try this in developer tools > template [![Open your Home Assistant instance and show your template developer tools.](https://camo.githubusercontent.com/47f3a8b580f1573997e8cd51002e17ac8fa3bf69eab78153eadc466fc9604ff0/68747470733a2f2f6d792e686f6d652d617373697374616e742e696f2f6261646765732f646576656c6f7065725f74656d706c6174652e737667)](https://my.home-assistant.io/redirect/developer_template/)
> 
> ```
> {% for l in states.light if l.name | lower == 'licht' %}
>   entity_id: {{ l.entity_id }} | name: {{ l.name }}{{ '\n' }}
> {% endfor %}
> ```
> 
> Does that return anything?

It doesn't return any entities. But it could indeed be one (or more) alias(es). What is the easiest way to check?

![image](https://github.com/home-assistant/intents/assets/43110823/4fb84f5f-bf72-4717-ac5f-f3dd967ff8fe)

**Comment by TheFes** [comment] 2023-07-17 13:05
in my test case, it does give the light for which I added the alias (used to reproduce your issue)
```yaml
intent:
  name: HassTurnOff
entities:
  name:
    name: name
    value: licht
    text: licht
targets:
  light.booglamp:
    matched: true 
```

**Comment by TheFes** [comment] 2023-07-17 13:06
@denniswham you can find the alias by using devtools > Assist (just above your last post) :)

**Comment by denniswham** [comment] 2023-07-17 13:09
I have removed the alias "licht" which was assigned to another entity. Now it all works, issues resolved 👍

**Comment by TheFes** [comment] 2023-07-17 13:10
Okay, great!

**Comment by denniswham** [comment] 2023-07-17 13:10
<img width="312" alt="image" src="https://github.com/home-assistant/intents/assets/43110823/e38435ae-408b-4804-879a-d56be0111334">

**Closed by TheFes** 2023-07-17 13:10 UTC
Labels: lang: nl

**Comment by synesthesiam** [comment] 2023-07-19 02:33
Thanks @TheFes! I was happy to see the dev tool helped 🙂

**Comment by TheFes** [comment] 2023-07-19 05:09
@synesthesiam
The devtools addition was indeed really useful here 

I still wonder why for turning on the sentence was parsed as `turn <expansion rule> <area> on` and for turning off as `turn <name> <area> off` How is decided which option is preferred, and why is it different in both cases.

**Comment by tetele** [comment] 2023-07-19 06:39
> I still wonder why for turning on the sentence was parsed as turn <expansion rule> <area> on and for turning off as turn <name> <area> off How is decided which option is preferred, and why is it different in both cases.

Sentences are parsed/matched in order, by filename and order inside the file. There is no priority system (maybe there should be?). I can't say for certain why the matching happened as it did, as I can't read enough Dutch to mentally match phrases, but keeping that in mind, you can probably try to do it yourself @TheFes.
